from __future__ import annotations

from types import SimpleNamespace

from lms_llmsTxt import analyzer


def test_build_dynamic_buckets_uses_default_branch_and_filters_dead_links(monkeypatch):
    recorded = []

    def fake_construct(repo_url, path, ref=None, style="blob"):
        recorded.append((repo_url, path, ref, style))
        return f"https://example.com/{ref or 'none'}/{path}"

    monkeypatch.setattr(analyzer, "construct_github_file_url", fake_construct)
    monkeypatch.setattr(analyzer, "_url_alive", lambda url: "keep" in url)

    file_tree = "docs/keep.md\nREADME.md\ntrash/missing.md"
    buckets = analyzer.build_dynamic_buckets(
        "https://github.com/example/repo",
        file_tree,
        default_ref="custom-branch",
        validate_urls=True,
    )

    # Only the URL containing 'keep' should remain after validation.
    assert any("keep.md" in url for _, items in buckets for _, url, _ in items)
    assert all("missing.md" not in url for _, items in buckets for _, url, _ in items)
    # construct_raw_url should receive the explicit default branch.
    assert all(ref == "custom-branch" for _, _, ref, _ in recorded if ref is not None)


def test_repository_analyzer_prefers_dspy_generation(monkeypatch):
    module = analyzer.RepositoryAnalyzer()

    module.analyze_repo = lambda **_: SimpleNamespace(
        project_purpose="Purpose",
        key_concepts=["concept-a", "concept-b"],
        architecture_overview="Architecture",
    )
    module.analyze_structure = lambda **_: SimpleNamespace(
        important_directories=["src/"],
        entry_points=["cli.py"],
        development_info="dev-info",
    )
    module.generate_examples = lambda **_: SimpleNamespace(usage_examples="example-usage")

    captured = {}

    def fake_generate_llms(**kwargs):
        captured.update(kwargs)
        return SimpleNamespace(llms_txt_content="# Project\n\n## Overview\nGenerated by DSPy")

    module.generate_llms_txt = fake_generate_llms

    result = module.forward(
        repo_url="https://github.com/example/repo",
        file_tree="README.md\nsrc/main.py",
        readme_content="# README",
        package_files="",
        default_branch="main",
    )

    assert result.generation_mode == "dspy"
    assert result.fallback_reason is None
    assert "Generated by DSPy" in result.llms_txt_content
    assert captured["architecture_overview"] == "Architecture"
    assert captured["important_directories"] == ["src/"]
    assert captured["entry_points"] == ["cli.py"]
    assert captured["development_info"] == "dev-info"
    assert captured["usage_examples"] == "example-usage"


def test_repository_analyzer_uses_heuristic_when_dspy_invalid(monkeypatch):
    module = analyzer.RepositoryAnalyzer()

    module.analyze_repo = lambda **_: SimpleNamespace(
        project_purpose="Purpose",
        key_concepts=["concept-a"],
        architecture_overview="Architecture",
    )
    module.analyze_structure = lambda **_: SimpleNamespace(
        important_directories=["src/"],
        entry_points=["cli.py"],
        development_info="dev-info",
    )
    module.generate_examples = lambda **_: SimpleNamespace(usage_examples="example-usage")
    module.generate_llms_txt = lambda **_: SimpleNamespace(llms_txt_content="")

    monkeypatch.setattr(analyzer, "_url_alive", lambda _: True)

    result = module.forward(
        repo_url="https://github.com/example/repo",
        file_tree="README.md\ndocs/guide.md",
        readme_content="# README",
        package_files="",
        default_branch="main",
    )

    assert result.generation_mode == "heuristic"
    assert result.fallback_reason == "invalid_or_empty_dspy_output"
    assert result.llms_txt_content.startswith("# Repo")
    assert "## Docs" in result.llms_txt_content
